// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Cz6QdTeRD1NKL7jD-LtbZ641kHxXoj8',
    appId: '1:111587241046:web:7ed3cfcd1fabde30a61ff7',
    messagingSenderId: '111587241046',
    projectId: 'gisoun-educational-app-001',
    authDomain: 'gisoun-educational-app-001.firebaseapp.com',
    storageBucket: 'gisoun-educational-app-001.appspot.com',
    measurementId: 'G-C4SYJB3DS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7opaWWlZ59GD23cphvDza9SdrHNfETJs',
    appId: '1:111587241046:android:50811734c5aa2ae6a61ff7',
    messagingSenderId: '111587241046',
    projectId: 'gisoun-educational-app-001',
    storageBucket: 'gisoun-educational-app-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0idhgwr8l4akqEVF9AdNUiWWxWJCtnU',
    appId: '1:111587241046:ios:309594f6635c8489a61ff7',
    messagingSenderId: '111587241046',
    projectId: 'gisoun-educational-app-001',
    storageBucket: 'gisoun-educational-app-001.appspot.com',
    iosClientId: '111587241046-t3cnkq22eohugv4e8v2v88q6nm463m98.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0idhgwr8l4akqEVF9AdNUiWWxWJCtnU',
    appId: '1:111587241046:ios:309594f6635c8489a61ff7',
    messagingSenderId: '111587241046',
    projectId: 'gisoun-educational-app-001',
    storageBucket: 'gisoun-educational-app-001.appspot.com',
    iosClientId: '111587241046-t3cnkq22eohugv4e8v2v88q6nm463m98.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationalApp',
  );
}
